# Generated by Django 4.2 on 2023-04-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Наименование категории")),
            ],
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории",},
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_code", models.TextField(verbose_name="Артикул")),
                ("name", models.TextField(verbose_name="Наименование")),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="instances",
                        to="product.category",
                        verbose_name="Категории",
                    ),
                ),
            ],
            options={
                "verbose_name": '"Экземпляр"',
                "verbose_name_plural": "Экземпляр",
            },
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
                ("count", models.IntegerField(verbose_name="Количество на складе")),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance",
                        to="product.instance",
                        verbose_name='"Экземпляр"',
                    ),
                ),
            ],
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары",},
        ),
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(verbose_name="Количество")),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods",
                        to="product.instance",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзина",},
        ),
        migrations.AddConstraint(
            model_name="instance",
            constraint=models.UniqueConstraint(
                fields=("vendor_code",), name="unique_vendor_code"
            ),
        ),
    ]
