# Generated by Django 4.2 on 2023-04-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="goods",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="product.instance",
                verbose_name="Предмет",
            ),
        ),
        migrations.RemoveField(model_name="userbasket", name="goods",),
        migrations.AddField(
            model_name="userbasket",
            name="goods",
            field=models.ManyToManyField(
                to="product.basket", verbose_name="Товары для покупки"
            ),
        ),
    ]
