# Generated by Django 4.2 on 2023-04-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_instance_options_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="categories",
            field=models.ManyToManyField(
                to="product.category", verbose_name="Категории"
            ),
        ),
    ]
